[2019-04-03 14:36:53,153][TCPserver:241] INFO [p2p] receive 50 blocks for BlockSyncGet from Peer(ip='39.97.166.176', port=9996)
[2019-04-03 14:36:54,175][TCPserver:243] INFO [p2p] 26 of 50 blocks from Peer(ip='39.97.166.176', port=9996) is new
[2019-04-03 14:36:54,279][TCPserver:640] INFO [p2p] creating a new side branch (idx 1) for block 0000076d119baec38805b97a003ccaeb22a97968b610a9ca8f5b8d990df10b00
[2019-04-03 14:36:54,323][TCPserver:264] INFO [p2p] 26 new blocks received are ['0000076d119baec38805b97a003ccaeb22a97968b610a9ca8f5b8d990df10b00', '00000387212a8ca62957c170646f2ede0605c2f234c50ec24fcfd5cb3e97706e', '0000010987d7a1f4951db7b47a50867278087bd8fd8b04791a501bb023dc9755', '00000308cf1bd903bb9170d42fb7f449696813eb687bcafcf1592179f1e45601', '000003abbc60fb242c731be1fef6c7f0184e009b9c70307c5e933b9d9fe1b846', '00000491b1acc9bddf0c187bfd34885d2bef6140b6d5e9b03a9063e22bd48e6e', '0000071afc4a13234145e171c7a3c056b38240a469b2b4b8c5471725f287f73b', '000004e0a627f36c8715a791a6533c1b839a90e968b8fea376da733dfebed0d8', '000005089c8788ce8893f2562a63509a8a738866403645c6e98ecd8f54183ff5', '000005fc9b07b97346c23fb59c32b3efd2752754727c6186e8f28823e219a82c', '0000028b61210223f827d8539e6ce73c672c8ddca5d57b40aa17096eb150aa6e', '000000126a1b205e3d287616c1b5b8b046a372415bf9fabd57ae74ec8cb4be36', '0000004c82f32f8281f604a8acf403c7d31a45113fa4e71859561dc1c24a5c44', '000006d7f6a6394ebe81e546f004eeb58e0990b2936f7a1de5c64675aa7a0494', '0000020f5cd2a55bdc8200f110c9e2bd235fd496ff0a363018e61d1b536351d6', '0000033a00cebc67d9050bf67240aafd100fb318c42b02e1009a73243716208f', '0000004746d9110caa1a8cefe4d6d9e712eb5c8c5545261137f6713dc97dcd6c', '000004280daf3d93083be0225fa1208310fdd4c606ef44b2ec5a28e8a1edc178', '000002bf36931afc2ead95c2e8ee6d816188d1c44a4d2e8812693a8f17b9d29a', '0000015c3ae5e3511e73e6ec710e44c612e4f6f6379d33b822b90905c4c00699', '0000059ee7c10ac354e7f5ecd72eba37ab10639b733180c9cd108f85e1fb2f2d', '0000018e9f9df073bce21c0d5a59723e184e5ada19764e734368c25f03475b2e', '000007a44097476b0753702f89ded015b1a0dd6ae2933149b1dd126afd37df0e', '00000296d651576990e4c2745f27b0551be00dcf5e801e5785da74b1e5f45af3', '00000398234de52e7aef864737a1e334afa6db1f1145260cebcc676c42a20d41', '000004f78e7a30bccbe911d01bd7be41dff558709f94d0b19447dd3db7b89391']
[2019-04-03 14:36:54,336][TCPserver:265] INFO [p2p] just append 25 blocks to side branch 1, leaving one block to be coped with method do_connect_block_and_after
[2019-04-03 14:36:54,337][BlockChain:142] INFO [ds] ## connecting block to chain with index #1: 000004f78e7a30bccbe911d01bd7be41dff558709f94d0b19447dd3db7b89391 
[2019-04-03 14:36:54,366][BlockChain:130] INFO [ds] decide to reorg branch 1 with height 897 to active_chain with real height 872
[2019-04-03 14:36:54,370][BlockChain:66] INFO [ds] block 000007836ed4d1e7866f0b2fd9411a0855f8c572a2b88723ec474e94397c9b32 disconnected, recover transactions and UTXOs by it
[2019-04-03 14:36:54,371][BlockChain:140] INFO [ds] ##### connecting block at height #872 chain with index #0: 0000076d119baec38805b97a003ccaeb22a97968b610a9ca8f5b8d990df10b00 
[2019-04-03 14:36:54,372][BlockChain:140] INFO [ds] ##### connecting block at height #873 chain with index #0: 00000387212a8ca62957c170646f2ede0605c2f234c50ec24fcfd5cb3e97706e 
[2019-04-03 14:36:54,376][BlockChain:140] INFO [ds] ##### connecting block at height #874 chain with index #0: 0000010987d7a1f4951db7b47a50867278087bd8fd8b04791a501bb023dc9755 
[2019-04-03 14:36:54,377][BlockChain:140] INFO [ds] ##### connecting block at height #875 chain with index #0: 00000308cf1bd903bb9170d42fb7f449696813eb687bcafcf1592179f1e45601 
[2019-04-03 14:36:54,378][BlockChain:140] INFO [ds] ##### connecting block at height #876 chain with index #0: 000003abbc60fb242c731be1fef6c7f0184e009b9c70307c5e933b9d9fe1b846 
[2019-04-03 14:36:54,383][BlockChain:140] INFO [ds] ##### connecting block at height #877 chain with index #0: 00000491b1acc9bddf0c187bfd34885d2bef6140b6d5e9b03a9063e22bd48e6e 
[2019-04-03 14:36:54,384][BlockChain:140] INFO [ds] ##### connecting block at height #878 chain with index #0: 0000071afc4a13234145e171c7a3c056b38240a469b2b4b8c5471725f287f73b 
[2019-04-03 14:36:54,393][BlockChain:140] INFO [ds] ##### connecting block at height #879 chain with index #0: 000004e0a627f36c8715a791a6533c1b839a90e968b8fea376da733dfebed0d8 
[2019-04-03 14:36:54,394][BlockChain:140] INFO [ds] ##### connecting block at height #880 chain with index #0: 000005089c8788ce8893f2562a63509a8a738866403645c6e98ecd8f54183ff5 
[2019-04-03 14:36:54,401][BlockChain:140] INFO [ds] ##### connecting block at height #881 chain with index #0: 000005fc9b07b97346c23fb59c32b3efd2752754727c6186e8f28823e219a82c 
[2019-04-03 14:36:54,402][BlockChain:140] INFO [ds] ##### connecting block at height #882 chain with index #0: 0000028b61210223f827d8539e6ce73c672c8ddca5d57b40aa17096eb150aa6e 
[2019-04-03 14:36:54,403][BlockChain:140] INFO [ds] ##### connecting block at height #883 chain with index #0: 000000126a1b205e3d287616c1b5b8b046a372415bf9fabd57ae74ec8cb4be36 
[2019-04-03 14:36:54,409][BlockChain:140] INFO [ds] ##### connecting block at height #884 chain with index #0: 0000004c82f32f8281f604a8acf403c7d31a45113fa4e71859561dc1c24a5c44 
[2019-04-03 14:36:54,410][BlockChain:140] INFO [ds] ##### connecting block at height #885 chain with index #0: 000006d7f6a6394ebe81e546f004eeb58e0990b2936f7a1de5c64675aa7a0494 
[2019-04-03 14:36:54,411][BlockChain:140] INFO [ds] ##### connecting block at height #886 chain with index #0: 0000020f5cd2a55bdc8200f110c9e2bd235fd496ff0a363018e61d1b536351d6 
[2019-04-03 14:36:54,412][BlockChain:140] INFO [ds] ##### connecting block at height #887 chain with index #0: 0000033a00cebc67d9050bf67240aafd100fb318c42b02e1009a73243716208f 
[2019-04-03 14:36:54,417][BlockChain:140] INFO [ds] ##### connecting block at height #888 chain with index #0: 0000004746d9110caa1a8cefe4d6d9e712eb5c8c5545261137f6713dc97dcd6c 
[2019-04-03 14:36:54,418][BlockChain:140] INFO [ds] ##### connecting block at height #889 chain with index #0: 000004280daf3d93083be0225fa1208310fdd4c606ef44b2ec5a28e8a1edc178 
[2019-04-03 14:36:54,419][BlockChain:140] INFO [ds] ##### connecting block at height #890 chain with index #0: 000002bf36931afc2ead95c2e8ee6d816188d1c44a4d2e8812693a8f17b9d29a 
[2019-04-03 14:36:54,420][BlockChain:140] INFO [ds] ##### connecting block at height #891 chain with index #0: 0000015c3ae5e3511e73e6ec710e44c612e4f6f6379d33b822b90905c4c00699 
[2019-04-03 14:36:54,425][BlockChain:140] INFO [ds] ##### connecting block at height #892 chain with index #0: 0000059ee7c10ac354e7f5ecd72eba37ab10639b733180c9cd108f85e1fb2f2d 
[2019-04-03 14:36:54,426][BlockChain:140] INFO [ds] ##### connecting block at height #893 chain with index #0: 0000018e9f9df073bce21c0d5a59723e184e5ada19764e734368c25f03475b2e 
[2019-04-03 14:36:54,427][BlockChain:140] INFO [ds] ##### connecting block at height #894 chain with index #0: 000007a44097476b0753702f89ded015b1a0dd6ae2933149b1dd126afd37df0e 
[2019-04-03 14:36:54,428][BlockChain:140] INFO [ds] ##### connecting block at height #895 chain with index #0: 00000296d651576990e4c2745f27b0551be00dcf5e801e5785da74b1e5f45af3 
[2019-04-03 14:36:54,429][BlockChain:140] INFO [ds] ##### connecting block at height #896 chain with index #0: 00000398234de52e7aef864737a1e334afa6db1f1145260cebcc676c42a20d41 
[2019-04-03 14:36:54,433][BlockChain:140] INFO [ds] ##### connecting block at height #897 chain with index #0: 000004f78e7a30bccbe911d01bd7be41dff558709f94d0b19447dd3db7b89391 
[2019-04-03 14:36:54,434][BlockChain:115] INFO [ds] chain reorg successful with new active_chain height 897 and top block id 000004f78e7a30bccbe911d01bd7be41dff558709f94d0b19447dd3db7b89391
[2019-04-03 14:36:54,434][TCPserver:570] INFO [p2p] a successful reorg is found, begin to deal with 1 side branches
[2019-04-03 14:36:54,556][TCPserver:612] INFO [p2p] ## delete 1 side branches beyond MAXIMUM_ALLOWABLE_HEIGHT_DIFF
[2019-04-03 14:36:54,560][TCPserver:294] INFO [p2p] current chain height 897, and continue initial block download ... 
[2019-04-03 14:36:54,880][TCPserver:324] INFO [p2p] succeed to send BlocksSyncReq to Peer(ip='39.97.166.176', port=9996)
[2019-04-03 14:36:54,913][PeerManager:62] INFO add log of result 0 from connecting to Peer(ip='39.97.166.176', port=9996)
[2019-04-03 14:36:54,928][TCPserver:341] INFO [p2p] received blocks from peer Peer(ip='39.97.166.176', port=9996)
[2019-04-03 14:36:54,934][TCPserver:241] INFO [p2p] receive 1 blocks for BlockSyncGet from Peer(ip='39.97.166.176', port=9996)
[2019-04-03 14:36:54,990][TCPserver:243] INFO [p2p] 1 of 1 blocks from Peer(ip='39.97.166.176', port=9996) is new
[2019-04-03 14:37:51,716][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='47.88.63.126', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 14:37:53,720][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.88.63.126', port=9996)
[2019-04-03 14:37:53,721][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.88.63.126', port=9996)
[2019-04-03 14:37:53,722][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.88.63.126', port=9996)
[2019-04-03 14:37:53,722][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.88.63.126', port=9996)
[2019-04-03 14:39:56,645][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.102.41.81', port=9996)
[2019-04-03 14:40:04,837][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='161.117.84.146', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 14:40:06,841][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='161.117.84.146', port=9996)
[2019-04-03 14:40:06,861][Utils:170] INFO [utils] succeed in sending to Peer(ip='39.97.166.176', port=9996) data about BlockRev in 1th time
[2019-04-03 14:40:06,863][PeerManager:62] INFO add log of result 0 from connecting to Peer(ip='39.97.166.176', port=9996)
[2019-04-03 14:42:17,956][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='47.111.168.213', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 14:42:19,960][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.111.168.213', port=9996)
[2019-04-03 14:42:19,961][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.111.168.213', port=9996)
[2019-04-03 14:42:20,986][Utils:121] ERROR [utils] ConnectionRefusedError(111, 'Connection refused'), failed to send to Peer(ip='47.92.85.186', port=10000) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
ConnectionRefusedError: [Errno 111] Connection refused
[2019-04-03 14:42:22,990][PeerManager:103] INFO [p2p] block Peer(ip='47.92.85.186', port=10000) in PeerManager
[2019-04-03 14:42:22,991][PeerManager:103] INFO [p2p] block Peer(ip='47.92.85.186', port=10000) in PeerManager
[2019-04-03 14:42:23,100][TCPserver:632] INFO [p2p]  block 00000645a9d82af1607ac15ef78195660c7a68a2414307c35aa6e577ca390da4 failed validation as an orphan block
[2019-04-03 14:42:23,101][EdgenceChain:245] INFO a mined block 00000645a9d82af1607ac15ef78195660c7a68a2414307c35aa6e577ca390da4 but failed validation
[2019-04-03 14:42:23,178][Consensus:25] INFO [consensus] mining after block 000004f78e7a30bccbe911d01bd7be41dff558709f94d0b19447dd3db7b89391
[2019-04-03 14:43:00,970][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.102.41.81', port=9996)
[2019-04-03 14:44:07,616][Consensus:38] INFO [consensus] mining block found at nonce=3555345 using 104.43806314468384 s at rate 34.0 KH/s: 000000ee409bd17a381dcf9aac64d21c585369d515a76675d07d50c86b3dd217
[2019-04-03 14:46:05,285][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='161.117.84.146', port=9996)
[2019-04-03 14:46:17,573][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='47.88.63.126', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 14:46:19,577][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.88.63.126', port=9996)
[2019-04-03 14:46:19,858][Utils:170] INFO [utils] succeed in sending to Peer(ip='39.97.166.176', port=9996) data about BlockRev in 1th time
[2019-04-03 14:46:19,859][PeerManager:62] INFO add log of result 0 from connecting to Peer(ip='39.97.166.176', port=9996)
[2019-04-03 14:48:30,692][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='47.111.168.213', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 14:48:32,697][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.111.168.213', port=9996)
[2019-04-03 14:49:09,605][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='161.117.84.146', port=9996)
[2019-04-03 14:50:43,813][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='47.102.41.81', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 14:50:45,817][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.102.41.81', port=9996)
[2019-04-03 14:52:13,924][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.88.63.126', port=9996)
[2019-04-03 14:52:56,932][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='161.117.84.146', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 14:52:58,937][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='161.117.84.146', port=9996)
[2019-04-03 14:52:59,046][BlockChain:140] INFO [ds] ##### connecting block at height #898 chain with index #0: 000000ee409bd17a381dcf9aac64d21c585369d515a76675d07d50c86b3dd217 
[2019-04-03 14:52:59,088][Consensus:25] INFO [consensus] mining after block 000000ee409bd17a381dcf9aac64d21c585369d515a76675d07d50c86b3dd217
[2019-04-03 14:53:15,062][Consensus:38] INFO [consensus] mining block found at nonce=815163 using 15.974468231201172 s at rate 51.0 KH/s: 000002b6aa8493ad063f8249f892f6d6797c123bd4c326f3b712e7d6af1ff2b1
[2019-04-03 14:55:18,244][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.102.41.81', port=9996)
[2019-04-03 14:55:24,389][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='161.117.84.146', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 14:55:26,393][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='161.117.84.146', port=9996)
[2019-04-03 14:55:26,403][Utils:170] INFO [utils] succeed in sending to Peer(ip='39.97.166.176', port=9996) data about BlockRev in 1th time
[2019-04-03 14:55:26,409][PeerManager:62] INFO add log of result 0 from connecting to Peer(ip='39.97.166.176', port=9996)
[2019-04-03 14:57:37,510][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='47.88.63.126', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 14:57:39,515][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.88.63.126', port=9996)
[2019-04-03 14:58:22,565][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.88.63.126', port=9996)
[2019-04-03 14:59:50,628][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='47.102.41.81', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 14:59:52,631][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.102.41.81', port=9996)
[2019-04-03 15:01:26,884][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='161.117.84.146', port=9996)
[2019-04-03 15:02:03,748][Utils:132] ERROR [utils] TimeoutError(110, 'Connection timed out'), failed to send to Peer(ip='47.111.168.213', port=9996) data about BlockRev  in 1th time
Traceback (most recent call last):
  File "/home/jin/.ssh/EdgenceChain/utils/Utils.py", line 116, in send_to_peer
    s.connect(peer())
TimeoutError: [Errno 110] Connection timed out
[2019-04-03 15:02:05,753][PeerManager:62] INFO add log of result 1 from connecting to Peer(ip='47.111.168.213', port=9996)
[2019-04-03 15:02:05,860][BlockChain:140] INFO [ds] ##### connecting block at height #899 chain with index #0: 000002b6aa8493ad063f8249f892f6d6797c123bd4c326f3b712e7d6af1ff2b1 
[2019-04-03 15:02:05,907][Consensus:25] INFO [consensus] mining after block 000002b6aa8493ad063f8249f892f6d6797c123bd4c326f3b712e7d6af1ff2b1
[2019-04-03 15:02:20,956][EdgenceChain:279] INFO [EdgenceChain] succeed to send TopBlockReq to Peer(ip='39.97.166.176', port=9996)
[2019-04-03 15:02:20,998][EdgenceChain:289] INFO [EdgenceChain] received top block from peer Peer(ip='39.97.166.176', port=9996)
[2019-04-03 15:02:21,023][TCPserver:433] INFO [p2p] received block 0000051e6e21f9777d4e81f3c18fe61b751f90f46bbb0c473e1c409ae5f6434e from peer Peer(ip='39.97.166.176', port=9996)
[2019-04-03 15:02:21,109][TCPserver:632] INFO [p2p]  block 0000051e6e21f9777d4e81f3c18fe61b751f90f46bbb0c473e1c409ae5f6434e failed validation as an orphan block
[2019-04-03 15:02:21,857][TCPserver:491] INFO [p2p] succeed to send TopBlocksSyncReq to Peer(ip='39.97.166.176', port=9996)
[2019-04-03 15:02:21,917][PeerManager:62] INFO add log of result 0 from connecting to Peer(ip='39.97.166.176', port=9996)
[2019-04-03 15:02:21,998][TCPserver:508] INFO [p2p] received blocks from peer Peer(ip='39.97.166.176', port=9996)
[2019-04-03 15:02:22,139][TCPserver:241] INFO [p2p] receive 50 blocks for BlockSyncGet from Peer(ip='39.97.166.176', port=9996)
[2019-04-03 15:02:23,805][TCPserver:243] INFO [p2p] 50 of 50 blocks from Peer(ip='39.97.166.176', port=9996) is new
[2019-04-03 15:02:23,899][TCPserver:632] INFO [p2p]  block 0000053b097f24f452a3526af0b3b38352b4a4b5613c411d378c1c6d9e73330b failed validation as an orphan block
